Repository pmz-q/est_wassup_03, pull requests merged in 2024-02, with the labels that each got.

#15 added: dirname & filename converter - text to uuid4
  utils/convert_label_to_coco.py
  utils/translate_filenames.py
Labels: new-feature

#19 bug fix: if img file does not exist, ignore the ann data
  utils/convert_label_to_coco.py
Labels: bug-fix

#22 수정: 서버에서 train 데이터 랜덤으로 일부 복사해오기
  utils/extract_imgs_from_train.py
Labels: feature-update

#23 Dev 20
  tools/convert_label_to_coco.py
  tools/extract_imgs_from_train.py
  tools/sample_data_into_yolo_structure.py
  tools/translate_filenames.py
Labels: feature-update

#25 added: yolo detection & edited: filename_translation + coco converter
  tools/convert_label_to_coco.py
  tools/create_feature_dataset.py
  tools/create_yolo_detection_dataset.py
  tools/translate_filenames.py
Labels: bug-fix, feature-update, new-feature

#27 added: yolo detection - train/val split
  tools/split_train_val.py
Labels: new-feature

#28 added: coco cls, det & yolo cls - train/val split
  tools/create_feature_dataset.py
  tools/create_yolo_detection_dataset.py
  tools/sample_data_into_yolo_structure.py
  tools/split_train_val.py
Labels: feature-update

#29 added: detect(inference only) face, crop face using YOLOv8
  tools/crop_face.py
  tools/detect_face.py
Labels: new-feature

#31 added: pipeline skeleton 1: training - yolo det, yolo cls
  .gitignore
  configs/project_1.yaml
  configs/project_2_yolo.yaml
  configs/project_3_yolo.yaml
  core/configs/__init__.py
  core/configs/model_config.py
  core/configs/resnet50_config.py
  core/configs/yolo_config.py
  core/datasets/__init__.py
  core/datasets/coco_classification_dataset.py
  core/models/__init__.py
  core/models/resnet50.py
  core/utils/__init__.py
  core/utils/engine.py
  core/utils/file_handler.py
  core/utils/transforms.py
  core/utils/utils.py
  data/.gitkeep
  inference/.gitkeep
  inference/inference_yolo_cls.py
  requirements.txt
  run.py
  tools/split_train_val.py
  train_tools/__init__.py
  train_tools/train_resnet50.py
  train_tools/train_yolo.py
  train_tools/train_yolo_cls.py
  utils/__init__.py
  utils/arg_parsers.py
Labels: new-feature

#42 fixed: bugfix - detection failure error case handling, delete default…
  tools/detect_face.py
Labels: bug-fix

#43 added: kpt_shape for use of pose estimation weight
  .gitignore
  tools/create_yolo_detection_dataset.py
  tools/split_train_val.py
Labels: bug-fix

#44 edited: split train val: logic updated for split after crop
  tools/convert_label_to_coco.py
  tools/detect_face.py
  tools/split_train_val.py
Labels: feature-update

#45 bug fix: yolo batch bug
  train_tools/train_yolo.py
  train_tools/train_yolo_cls.py
Labels: bug-fix

#68 added: dlib inference
  configs/project_1.yaml
  configs/project_2_yolo.yaml
  configs/project_3_yolo.yaml
  core/configs/model_config.py
  infer_tools/__init__.py
  infer_tools/infer_dlib_det.py
  requirements.txt
  run.py
  tools/sync_coco_annot_with_imgs.py
Labels: new-feature

#69 updated: dlib: bugs....
  configs/project_1.yaml
  configs/project_2_yolo.yaml
  configs/project_3_yolo.yaml
  core/configs/model_config.py
  infer_tools/infer_dlib_det.py
  requirements.txt
  run.py
Labels: bug-fix

#71 edited: dlib: save heatmap jpg, color&gray img w/ keypoints
  configs/project_1.yaml
  configs/project_2_yolo.yaml
  configs/project_3_yolo.yaml
  core/configs/model_config.py
  infer_tools/infer_dlib_det.py
Labels: feature-update

#72 fixed: resnet error & edited: resnet: dropout added
  core/configs/resnet101_config.py
  core/configs/resnet152_config.py
  core/configs/resnet50_config.py
  core/models/resnet101_cls.py
  core/models/resnet152_cls.py
  core/models/resnet50_cls.py
  infer_tools/infer_resnet101_cls.py
  infer_tools/infer_resnet152_cls.py
  infer_tools/infer_resnet50_cls.py
  train_tools/train_resnet101_cls.py
  train_tools/train_resnet152_cls.py
  train_tools/train_resnet50_cls.py
Labels: bug-fix

#74 added: demo script: crop image
  demo.py
  demo_tools/__init__.py
  demo_tools/classification.py
  demo_tools/crop_image.py
  demo_tools/input_images/example.jpg
  demo_tools/results/2d_generated/.gitkeep
  demo_tools/results/classified/.gitkeep
  demo_tools/results/cropped/.gitkeep
  demo_tools/weights/2d_weight/.gitkeep
  demo_tools/weights/3d_weight/.gitkeep
  demo_tools/weights/classifier_weight/.gitkeep
  demo_tools/weights/crop_weight/.gitkeep
  requirements.txt
Labels: new-feature
